//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionStationsCRMUG
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_ApplyCreditLimit")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
	public partial class new_ApplyCreditLimitRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.Money RequestedCreditLimit
		{
			get
			{
				if (this.Parameters.Contains("RequestedCreditLimit"))
				{
					return ((Microsoft.Xrm.Sdk.Money)(this.Parameters["RequestedCreditLimit"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Money);
				}
			}
			set
			{
				this.Parameters["RequestedCreditLimit"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_ApplyCreditLimitRequest()
		{
			this.RequestName = "new_ApplyCreditLimit";
			this.RequestedCreditLimit = default(Microsoft.Xrm.Sdk.Money);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}